In [1]:
# array ojbect in Numpy => ndarray

# In computer science, locality of reference, 
# also known as the principle of locality, is the 
# tendency of a processor to access the same set 
# of memory locations repetitively over a short period of time.

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(np.__version__)

print(type(arr)) # numpy.ndarray

[1 2 3 4 5]
1.26.3
<class 'numpy.ndarray'>


In [3]:
# 0-D arrays
arr1 = np.array(23)

# 1-D arrays
arr2 = np.array([1, 2, 3, 4, 5])

# numpy has a whole sub module dedicated towards matrix operations => numpy.mat
print(arr1, arr2)

23 [1 2 3 4 5]


In [4]:
print(arr2.ndim)

# n-D arrays 
arr3 = np.array([1, 2, 3, 4, 5], ndmin=5) # [[[[[1 2 3 4 5]]]]]

print(arr3)

1
[[[[[1 2 3 4 5]]]]]


In [5]:
# data type in numpy
print(arr.dtype) #int32

arr4 = np.array([2, "a"]) 
print(arr4.dtype) # <U11

arr5 = np.array([1, 2, 3, 4, 5], dtype='i4')

int32
<U11


In [6]:
# changing datatype of existing array
newarr = arr5.astype('f') # creating a copy

print(newarr)

[1. 2. 3. 4. 5.]


In [7]:
x = arr.copy()
y = arr.view()
print(x.base, y.base) # will return None if array owns the data otherwise will return original array

None [1 2 3 4 5]


In [8]:
print(arr.shape, arr3.shape)

(5,) (1, 1, 1, 1, 5)


In [9]:
newarr = arr.reshape(1, 5)
print(newarr)

[[1 2 3 4 5]]


In [12]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr3 = np.concatenate((arr1, arr2), axis=0) # creates new rows 
arr4 = np.concatenate((arr1, arr2), axis=1) # creates new columns
print(arr3, arr4)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]] [[1 2 5 6]
 [3 4 7 8]]


In [16]:
arr1 = np.array([[[1, 2], [3, 4]], [[9, 10], [11, 12]]])

arr2 = np.array([[[5, 6], [7, 8]], [[13, 14], [15, 16]]])

arr3 = np.concatenate((arr1, arr2), axis=0) # creates new rows 
arr4 = np.concatenate((arr1, arr2), axis=1) # creates new columns
print(arr3, "h\n",arr4)

[[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]]

 [[13 14]
  [15 16]]] h
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
